# Generated by Django 3.2.13 on 2022-05-18 11:59

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, verbose_name='Venue Name')),
                ('venue_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('address', models.CharField(max_length=290)),
                ('zip_code', models.CharField(max_length=20, verbose_name='Zip Code')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_date', models.DateTimeField(verbose_name='Concert Date')),
                ('name', models.CharField(max_length=130, verbose_name='Concert Name')),
                ('concert_information', models.TextField(blank=True)),
                ('concert_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('concert_goers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='booking.venue')),
            ],
        ),
    ]
