# Generated by Django 3.2.13 on 2022-05-23 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20220522_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='quanty',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
