# Generated by Django 3.2.13 on 2022-05-24 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20220524_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='total_left',
        ),
        migrations.AddField(
            model_name='concert',
            name='total_left',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
