# Generated by Django 3.2.13 on 2022-05-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20220524_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='total_left',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
