# Generated by Django 3.2.13 on 2022-05-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20220525_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.IntegerField(),
        ),
    ]
