# Generated by Django 3.2.13 on 2022-05-27 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_ticket_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='total_left',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
